In [1]:
import pandas as pd

DATA_PATH = "../../data/jb-swisshacks2024/"
is_fake_data = pd.read_csv(DATA_PATH + "fake_audio_classification_results.csv")
is_factually_correct = pd.read_csv(DATA_PATH + "fact_checks_v2.csv")

In [2]:
# Extract the FINAL_LABEL column and rename it to is_fake
is_fake_data['is_fake'] = is_fake_data['FINAL_LABEL'].apply(lambda x: True if x == 1 else False)

# keep only is_fake and ID columns
is_fake_data = is_fake_data[['ID', 'is_fake']].rename(columns={'ID': 'rec_id'})
is_fake_data

         rec_id  is_fake
0    XATHQAOSPE     True
1    D7ATV3H1YD     True
2    DXUFMO00FS     True
3    NZBALVR6CF    False
4    TKWJHEYRLP     True
..          ...      ...
395  V1Q3EL4Z4X     True
396  IH6195R5YX     True
397  5KLHR74OI0     True
398  KTG9DOE0M2    False
399  572K7GROWM     True

[400 rows x 2 columns]

In [3]:
df_fake_and_facts = pd.merge(is_fake_data, is_factually_correct, on="rec_id")

# transform is_factually_correct from 'no' to False and 'yes' to True
df_fake_and_facts['is_factually_correct'] = df_fake_and_facts['is_factually_correct'].apply(lambda x: True if x == 'yes' else False)

# keep only the rec_id, is_fake and is_factually_correct columns
df_fake_and_facts = df_fake_and_facts[['rec_id', 'is_fake', 'is_factually_correct']]
df_fake_and_facts

         rec_id  is_fake  is_factually_correct
0    XATHQAOSPE     True                 False
1    D7ATV3H1YD     True                  True
2    DXUFMO00FS     True                 False
3    NZBALVR6CF    False                  True
4    TKWJHEYRLP     True                  True
..          ...      ...                   ...
395  V1Q3EL4Z4X     True                  True
396  IH6195R5YX     True                 False
397  5KLHR74OI0     True                 False
398  KTG9DOE0M2    False                  True
399  572K7GROWM     True                 False

[400 rows x 3 columns]

In [4]:
# export the final dataframe
df_fake_and_facts.to_csv(DATA_PATH + "prefinal_is_fake_and_facts.csv", index=False)